deploy_to_lightsail:
  stage: deploy
  image: alpine  # Imagen ligera con SSH
  before_script:
    - apk add --no-cache openssh-client rsync  # Instala SSH
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -  # Carga la clave
    # $SSH_PRIVATE_KEY: GitLab inyectará el contenido de tu clave como un archivo temporal.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@54.158.56.182NCIA << EOF
      cd /home/ubuntu/tu-repo-astro
      git pull origin develop
      npm install
      npm run build
      sudo cp -r dist/* /var/www/html/
      EOF
  only:
    - develop  # Solo se ejecuta en pushes a main