image: node:18

stages:
  - build
  - deploy

before_script:
    - eval $(ssh-agent -s)  # Inicia el agente SSH
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -  # Añade la clave privada al agente
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 54.158.56.182 >> ~/.ssh/known_hosts  # Agrega el servidor a known_hosts
    - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  script:
    - npm install
    - npx astro build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - rsync -avz --delete dist/ ubuntu@54.158.56.182:/var/www/html/
